[WIP] 枝切り実装
n4o847/seccamp-redos pull request #25
Opened 2020-11-27 09:20 UTC by yuziroppe

今現在枝切り実装が完了したが、もとのテストケースで`EDA: positive`のやつも`false`になってしまっている。
検証始めます。

また三浦くんが作ったredefine_state_2の新規Stateをもとに実装しております。

2020-11-27 09:54 UTC, yuziroppe commented
q0からある文字charで一度でもどこかに遷移したらその他の遷移を考えなくなっちゃっているな。。。
目的のStateが違うときはちゃんと遷移しないといけない

2020-11-27 10:08 UTC, yuziroppe commented
完全に同じ遷移じゃない限りは遷移を生やすことができるという制約を見逃していた
TransitionMapクラスにhasメソッドを作って対応した(同じ辺は存在しても1つなので計算量的にlog(sourceの個数)×log(charの個数)になっているから問題もないはず)

2020-11-27 10:20 UTC, yuziroppe commented
もとの検出と比較したところ残りは`(a*)*`と`(a+)+`に。
なんとなく二重辺壊しているような予感がする。
あと逆に新しく追加した`(.*|(a|a)*)`がVulnerableになってしまった。

2020-11-27 12:13 UTC, MakeNowJust commented
@yuziroppe `/^(.*|(a|a)*)$/s` だとsafeなはずです。(JavaScriptの正規表現の`.`はデフォルトでは改行文字を含まないため)

2020-11-28 04:21 UTC, MakeNowJust requested changes
気になったところをコメントしました

2020-11-28 04:21 UTC, MakeNowJust commented on src/types.ts
> +export type LeafCutNFA = {
LeafCutという名前では枝刈りの意図は伝わりません。(leafは葉ですし、cutはグラフ理論的に意味のある言葉なので、全面的に良くないと思います)

枝刈りは英語では"prunning"が一般的です。

2020-11-28 04:21 UTC, MakeNowJust commented on src/cutLeaf.ts
> +          dfaSourceSet.has(q1) &&
ここで `dfaSourceSet.has(q1)` としている理由が分かりません。
スライドの遷移関数の定義の赤字の部分のつもりであれば間違っています。

![スクリーンショット 2020-11-28 13 20 37](https://user-images.githubusercontent.com/6679325/100493671-90cd2000-317c-11eb-9f05-237c2850b2f0.png)

2020-11-28 05:01 UTC, yuziroppe commented on src/cutLeaf.ts
> +          dfaSourceSet.has(q1) &&
@MakeNowJust dfaSourceSetというのがQ''であるので、δ(q,σ)つまりnfaDestListを見ていって、nfaDestList内で一番最初にdfaSourceSet内に含まれるq1へ遷移する辺を追加したいという自分の意図なのですが、もう少し間違っている理由を教えて頂けると助かります

2020-11-28 05:13 UTC, MakeNowJust commented on src/cutLeaf.ts
> +          dfaSourceSet.has(q1) &&
あ、`break`してるのか。なら間違ってないと思います。

2020-11-28 10:44 UTC, yuziroppe commented
残りのTODO(恐らく)
 - pruning後に生成されたNFAから初期状態を通らないノード遷移を削除する
- masterをmergeしてコンフリクトを直す...

2020-11-28 13:05 UTC, yuziroppe commented
枝刈りでEDA謝検知は防げたが、IDA positiveがSafeになるな...

2020-11-28 13:19 UTC, yuziroppe commented
`a*a*`
枝刈り後もIDA構造を持っているのに検出されないは草

2020-11-28 13:29 UTC, yuziroppe commented
VIzでデバッグしたら完全理解した。枝切りNFAにして状態表示方法が変わったから、それに対応して比較させないと行けない

2020-11-28 13:40 UTC, yuziroppe commented
枝刈り正しく検知するようになりました！
もしよろしければマージお願いします

2020-11-28 14:20 UTC, n4o847 commented
うおおお疲れさまです！

2020-11-28 14:28 UTC, n4o847 commented on src/transitions.ts
> +  }
`TransitionMap` は「JavaScript で `Map<[A, B], C>` ができないから `Map<A, Map<B, C>>` を使い、そのままだと面倒だからラップしたものとして用意した」くらいのものなので、あまり自明でないメソッドをぽこぽこ生やすのはちょっと抵抗があるというのが正直なところです……

まあでも「こういうメソッドほしい」みたいなのは確かにあるかもしれないしあまり拒否はできないですね、うーむ

2020-11-28 14:28 UTC, n4o847 commented on src/types.ts
>  };
細かいですが、枝刈りされたNFAなので `PruningNFA` より `PrunedNFA` のほうがいい気がします

2020-11-28 16:23 UTC, n4o847 commented on src/transitions.ts
> +  }
これってつまり、遷移元／文字／遷移先のどれか2つを指定して残り1つを得たいんですよね

本当は `for (const q of stateList) ` とか `for (const a of alphabet)` みたいなループの組み合わせでやってほしいところですが、それだと複雑になりますかね……。

2020-11-28 17:01 UTC, yuziroppe commented on src/transitions.ts
> +  }
これ、pruning.ts側にこいつらを移行して、引数でTransitionMapを取ると欲しい情報を返す関数するとまだましになるかもです。
今現在他の用途で`getTuplesFromChar `と`getSourceCharTuples`は使わないし局地的なので。
しかし`getTransitions`は使いたくて(TransitionMapクラス外にsourceだけを引数にとって複数遷移を取る関数を実装できないため(mapが隠蔽されている))。`has`は使っていないので一旦消しておきます。

2020-11-28 17:17 UTC, yuziroppe commented on src/transitions.ts
> +  }
追記です
せめてmapのキーを全取得は欲しいのでkeysのような普遍的な関数を用意して、それを使って外部で呼び出すみたいにします

2020-11-28 17:27 UTC, n4o847 commented on src/transitions.ts
> +  }
`keys` はたしかに標準の `Map` にもあるものなのでわかる気がします

キーの隠蔽については、もともと `for (const q of stateList)` や `for (const a of alphabet)` のようなループの組み合わせでやってもらう想定でした

2020-11-28 17:37 UTC, yuziroppe commented on src/transitions.ts
> +  }
うーん、`for (const q of stateList)` や `for (const a of alphabet)` のようなループの組み合わせだと必ずしも、qとaのペアが辺になっているという確証が取れないので、Map<[A, B], C>の[A, B]とは違う気がするなあと思ってしまいます。。

2020-11-28 17:41 UTC, n4o847 commented on src/transitions.ts
> +  }
そしたら `transitions.get(q, a)` が `[]` になるので良い気がします

まあでも今回は要素が必ずある δ(q, a) を抜き出したいのか…

2020-11-28 18:01 UTC, yuziroppe commented on src/transitions.ts
> +  }
すべてのstateListとalphabetの組に対してtransitions.get(q, a)が存在するか取り、filterをかけるみたいなことも一応できるのか、、
一旦、折衷案としてkeysとgetTransitionsという関数を作ってみました、少しはマシになるかな。。

2020-11-28 18:10 UTC, n4o847 commented on src/transitions.ts
> +  }
大丈夫だと思います！

（なんか変なところにこだわって本質が進まないのも申し訳ないのでこの辺にします）

2020-11-28 18:16 UTC, n4o847 approved these changes

2020-11-29 09:02 UTC, masa5555 commented on src/pruning.ts
> +  }
一つネストが多いのはなにか意味があるんでしょうか？（自分が知らないだけなのかも知れませんが）

2020-11-29 09:34 UTC, yuziroppe commented on src/pruning.ts
> +  }
これは、初期状態を作るために必要な部分を切り分けたかったからですね、(初期状態を作るためにのみこの変数を利用していると明示したかった)

2020-11-29 09:40 UTC, n4o847 commented on src/pruning.ts
> +  }
明示的にスコープを狭めることでわかりやすくなっていると個人的には思います
（あんまり詳しくは無いですが、多分他の言語の慣習とかからの輸入？）

2020-11-29 09:44 UTC, yuziroppe commented on src/pruning.ts
> +  }
CやC++でこういう書き方を使ってて、TSにも取り込みました

2020-11-29 09:46 UTC, masa5555 commented on src/pruning.ts
> +  }
なるほど、勉強になります！

2020-11-29 09:47 UTC, masa5555 approved these changes

2020-11-29 12:19 UTC, merged